name: CI-C

on:
  workflow_dispatch:
  
  push:
    branches: 
      - "main"
  
jobs:
  
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Setup Cpp (C++ / C)
        uses: aminya/setup-cpp@v0.26.2
        with:
          compiler: gcc
          make: true
          cache: cppcache
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.4.0

      - name: build main
        run: make main --directory=C

      - name: build project
        run: make --directory=C

      - run: echo Calculation && ./C/output/bin/calculation
        continue-on-error: true
      - run: echo Ecrire && ./C/output/bin/ecrire
        continue-on-error: true
      - run: echo Lire && ./C/output/bin/lire
        continue-on-error: true
      - run: echo Si && ./C/output/bin/si
        continue-on-error: true
     #- run: echo TantQue && ./C/output/bin/tantque
     #  continue-on-error: true
      - run: echo Fonction && ./C/output/bin/fonction
        continue-on-error: true


