name: CI-C

on:
  workflow_dispatch:
  push:

  
jobs:
  
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Setup Cpp (C++ / C)
        uses: aminya/setup-cpp@v0.26.2
        with:
          compiler: gcc
          make: true
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.4.0

      - run: cd C && python3 juge.py
        continue-on-error: true