name: CI-C

on:
  workflow_dispatch:
  
  push:
    branches: 
      - "main"
  
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Cpp (C++ / C)
        uses: aminya/setup-cpp@v0.26.2
        with:
          compiler: gcc
          make: true
          cache: cppcache
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.4.0


      - name: build main
        run: make main --directory=C

      - name: build project
        run: make --directory=C

      - run: sudo exec ./C/output/exemple1.o
        continue-on-error: true
      - run: sudo exec ./C/output/exemple2.o
        continue-on-error: true
      - run: sudo exec ./C/output/exemple3.o
        continue-on-error: true
      - run: sudo exec ./C/output/exemple4.o
        continue-on-error: true

