name: CI-C

on:
  workflow_dispatch:
  
  push:
    branches: 
      - "main"
  
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Cpp (C++ / C)
        uses: aminya/setup-cpp@v0.26.2
        with:
          compiler: gcc
          make: true
          cache: cppcache
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.4.0

      - name: build main
        run: make main --directory=C

      - name: build project
        run: make --directory=C

      - run: echo Ex1 && ./C/output/bin/exemple1
      - run: echo Ex2 && ./C/output/bin/exemple2
      - run: echo Ex3 && ./C/output/bin/exemple3
      - run: echo Ex4 && ./C/output/bin/exemple4
      - run: echo Ex5 && ./C/output/bin/exemple5


